In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)

[[19 22]
 [43 50]]


In [6]:
print(result)

[[19 22]
 [43 50]]


In [7]:
transposed = np.transpose(A)
print(transposed)

[[1 3]
 [2 4]]


In [8]:
inverse = np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues, eigenvectors)

[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [22]:
determinant = np.linalg.det(A)
print(determinant)

-2.0000000000000004


In [23]:
b = np.array([1, 2])
solution = np.linalg.solve(A, b)

print(solution)

[0.  0.5]


In [24]:
U, S, V = np.linalg.svd(A)

print(U, S, V)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]] [5.4649857  0.36596619] [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [25]:
rank = np.linalg.matrix_rank(A)
print(rank)

2


In [26]:
x = np.linspace(0, 10, 100)
y = np.sin(x)

dy_dx = np.gradient(y, x)

print(dy_dx)

[ 0.99830036  0.99321184  0.97799815  0.95281439  0.91791729  0.8736626
  0.82050147  0.75897585  0.68971295  0.61341886  0.53087135  0.44291195
  0.35043734  0.25439024  0.15574979  0.05552157 -0.04527265 -0.14560535
 -0.2444537  -0.34080999 -0.43369194 -0.52215268 -0.6052904  -0.68225756
 -0.75226954 -0.81461261 -0.86865122 -0.91383447 -0.94970177 -0.97588745
 -0.99212457 -0.99824762 -0.99419416 -0.98000551 -0.95582633 -0.92190311
 -0.87858166 -0.82630363 -0.76560196 -0.69709546 -0.62148251 -0.53953394
 -0.45208516 -0.36002765 -0.2642999  -0.16587777 -0.06576463  0.03501895
  0.13544553  0.23449132  0.33114663  0.4244261   0.51337882  0.59709797
  0.67473008  0.74548374  0.80863767  0.86354805  0.9096551   0.94648879
  0.97367362  0.99093247  0.99808939  0.99507142  0.98190932  0.95873728
  0.92579151  0.88340789  0.83201848  0.77214717  0.7044043   0.62948048
  0.54813951  0.46121059  0.36957993  0.27418163  0.17598823  0.07600073
 -0.02476154 -0.12527139 -0.22450417 -0.32144828 -0.

In [27]:
coefficients = [1, -6, 11, -6]  # x^3 - 6x^2 + 11x - 6 = 0
roots = np.roots(coefficients)

print(roots)

[3. 2. 1.]


In [28]:
array = np.array([1, 2, 3, 4])
cumulative_sum = np.cumsum(array)

print(cumulative_sum)

[ 1  3  6 10]


In [29]:
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)

print(mean_value)

3.0


In [32]:
std_dev = np.std(data)

print(std_dev)

1.4142135623730951


In [33]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])

covariance_matrix = np.cov(x, y)

print(covariance_matrix)

[[1.66666667 3.33333333]
 [3.33333333 6.66666667]]
